
<?php //echo $this->action('calendriermensuel','calendrier','application'); ?>
	

	<div id ="bloc_choix_personne">
		<h4><?php echo $this->escape($this->title);?></h4>
				<div id="filtres_personne">
					<ol>
						</br>
						<li><strong>Nom</strong></li>
						</br>
						<li><strong>Prenom</strong></li>
						</br>
						<li><strong>Entree en :</strong></li>
						</br>
						<li><strong>Entite</strong></li>
						</br>
						<li><strong>Pole</strong></li>
					</ol>			
				</div>
				<div id="filtres_personne2">
					<ol>
						</br>
						<li><strong>Fonction</strong></li>
						</br>
						<li><strong>FO/BO(disabled)</strong></li>
						</br>
						<li><strong>Modalite</strong></li>
						</br>
						<li><strong>Pourcentage</strong></li>
						</br>
						<li><strong>Stagiaire</strong></li>
																									
					</ol>			
				</div>
	
	<?php echo $this->form; ?>	
	</div>


