
<?php 



///////////Function recupére les jours fériés maroc///////////
/*  echo 'les jours fériés Maroc </br>';
	for ($i = 0; $i <  count($this->var); $i++) 
	{
		echo $this->var[$i]['date_debut'].'</br>' ;
	}
*/



///////////Function jours_feries($annee, $alsacemoselle=false, $maroc=false)///////////
/*   echo 'les jours fériés Maroc / France selon le cas ! </br>';
   
   for ($i = 0; $i <  count($this->var); $i++) 
	{
   		// multidimentionnel		
  		 if ((count($this->var,COUNT_RECURSIVE) - count($this->var,COUNT_NORMAL) > 0 ))    
   		{
  			 	echo $this->var[$i]['date_debut'].'</br>' ;  
   		}
   		// multidimentionnel
  		 else                
 	    {
  			   echo $this->var[$i].'</br>' ;
  	    }
	
	}
*/

///////////Function est_ferie($jour, $alsacemoselle, $maroc)
/*     echo 'tester si un jour est férié ou non ! </br>';
    echo " le jour est il férié ?  :".$this->var;  */ 


///////////Function calcul_nombre_jours_conges///////////
/*e
echo 'Calculer le nombre de jours entre deux dates ! </br>'; 
echo $this->var;
*/


///////////Function a_normaliser($date,$maroc)
/*
    echo " le jour à normaliser :".$this->var;   
*/

///////////Function  normaliser_date_debut_conge($date,$maroc)
//    print_r($this->var);   

    
    
///////////Function  normaliser_date_fin_conge($date,$maroc)
//	  print_r($this->var);   
    

?>



 


