<div>
    <table border="1">
        <tr>
            <th>id</th>
            <th>Login</th>
            <th>password</th>
            <th>edit</th>
            <th>delete</th>
        </tr>
        <?php
            //$this->usersArray est une variable qui peut être garnie par le controller
            //elle doit recevoir un tableau contenant des objets de type Default_Model_Users
            //le tableau est parcouru par foreach pour afficher les propiétés des objets contenus dans le tableau
            foreach ($this->profilArray as $users) :
        ?>
        <tr>
            <td><?php echo $profil->id; ?></td>
            <td><?php echo $profil->login; ?></td>
            <td><?php echo $profil->password; ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'profil', 'action' => 'edit', 'id' => $profil->id), 'default', true); ?>">Edit</a>
            </td>
           <td>
                <a href="<?php echo $this->url(array('controller' => 'profil', 'action' => 'delete', 'id' => $profil->id), 'default', true); ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php
    //nous affichons, à la suite du tableau (après la balise </table>), notre template qui permettra de gérer la pagination
    //la méthode pginationControl() prend, ici, 3 arguments:
    //  - l'instane paginator
    //  - le style de défilement
    //  - le template de pagination
    echo $this->paginationControl($this->profilArray, 'Sliding', 'common/my_paginator_control.phtml');
	?>
</div>
