<?php if ($this->pageCount): ?>

 <div  id="paginationControl" class="pagination">
<ul>

<?php if (isset($this->previous)): ?>
<li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">Précédent</a></li>

<?php endif; ?>
<?php foreach ($this->pagesInRange as $page): ?>
 <?php if ($page != $this->current): ?>
<li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
<?php else: ?>
<li><a style="font-size:16px;" href="#"><?php echo $page; ?> </a></li>
<?php endif; ?>
<?php endforeach; ?>
<?php if (isset($this->next)): ?>
<li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">Suivant</a></li>
<?php else: ?>

</ul>
<?php endif; ?>
</div>
<?php endif; ?>
