<?php if ($this->pageCount): ?>
<div id="paginationControl">
 
<!-- Lien vers page précédente -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; <?php echo "précédent"; ?></a> |
<?php else: ?>
  <span class="disabled">&lt; <?php "précédent"; ?></span> |
<?php endif; ?>
 
<!-- Liens numéros de page -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> |
  <?php else: ?>
    <span class="current"><?php echo $page; ?></span> |
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Lien vers page suivante -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo "suivant" ?> &gt;</a>
<?php else: ?>
  <span class="disabled"><?php echo "suivant"; ?> &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>