<?php 
$this->headScript()->appendFile( $this->baseUrl() .'/js/myScriptCong.js');
echo $this->headScript();
?>
<!-- Modal Pour confirmation de suppression -->
 <div id="myModal" class="modal message hide fade" aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" style="display: none;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		<h3 id="myModalLabel">Confirmer la suppression</h3>
	</div>
	<div class="modal-body">
		<p></p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true" id="annulSupp">Annuler</button>
		<button class="btn  btn-info" id="suppButton">Confirmer</button>
	</div>
</div>
<div class="row-fluid offset1">
		<div id="header-container">
            
			<div class="dropdown">
                  <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown"  >
                     Conge
                  </a>
                 
			</div><!--MBA : fermeture dropdown -->
          
		</div><!-- MBA : fermeture div="header-container" -->
	</div><!-- MBA : fermeture div="row-fluid -->
         <br/>
<div class="container">
		<div class="well row-fluid">
		<h2>Liste des Conges :</h2><br/>
<?php
	/*
	 * Si erreurs de traitements* renvoyé depuis le controlleur 
	 * traitemets : logique, ajout BD, Exception ...
	 */

	if(isset($this->error))
	{ 
	?>
	
      <!-- afficage alerte avec message d'erreur -->
			<div class="alert alert-error">
				<button type="button" class="close " data-dismiss="alert"></button>
				<strong>Erreur :</strong>  <?php //Message d'erreur
                                         echo "   ".$this->error; ?>
			</div>

	<?php } ?>

	<?php
	
	/*
	 * Gestion des messages warnings 
	 */

	if(isset($this->warning)){ 
	?>
	
      <!-- afficage alerte avec message d'erreur -->
			<div class="alert">
				<button type="button" class="close " data-dismiss="alert"></button>
				<strong>Alerte :</strong>  <?php //Message warning
                                         echo "   ".$this->warning; ?>
			</div>
	
	<?php } 
	 
	
	
 	/*
	 * Gestion des messages succès 
	 */
	
	else if(isset($this->success))
	{
	?>
	
	<!-- afficage message succés  -->
            <div class="alert alert-success">
				<button type="button" class="close " data-dismiss="alert"></button>
				<strong>Succes :</strong> <?php //Message succes
	                                      echo "   ".$this->success ;?>
			</div>
	<?php }?>
<div>
    <table  class="table table-hover ">
        <thead> 
        <tr>
            <th>Id</th>
            <th>Nom Prenom</th>
            <th>Type de conge</th>
            <th>Annee Reference</th>
            <th>Date Debut</th>
            <th>Date Fin</th>
            <th>Debut Journee</th>
            <th>Fin Journee</th>
            <th>Nombre Jours</th>
            <th>Ferme</th>
            <?php 
               $profil = substr_replace($this->LoggedProfil(),"",0,31);
               $profil = str_replace("Deconnexion","", $profil);
               $profil = str_replace(" ","",$profil);
               $profil  = strip_tags($profil);
            
               if($profil == 'admin')
            {
            	echo "<th>Modifier</th>";
                echo "<th>Supprimer</th>";
            
            } 
            ?>
 
        </tr>
         </thead> 
        <?php

            //$this->usersArray est une variable qui peut être garnie par le controller
            //elle doit recevoir un tableau contenant des objets de type Default_Model_Users
            //le tableau est parcouru par foreach pour afficher les propiétés des objets contenus dans le tableau
            foreach ($this->congeArray as $conge) :
            $personne = new Default_Model_Personne();
			$result_set_personnes = $personne->find($conge->id_personne);
			$type = new Default_Model_TypeConge();
			$result_set_types = $type->find($conge->id_type_conge);
         
         ?>
        <tbody> 
        <tr id="<?php echo $conge->id; ?>">
            <td><?php echo $conge->id_personne; ?></td>
            <td><?php echo $result_set_personnes->getNom().'  '.$result_set_personnes->getPrenom(); ?></td>  
            <td><?php echo $result_set_types->getCode(); ?></td>
            <td><?php echo $conge->annee_reference; ?></td>
            <td><?php echo $conge->date_debut; ?></td>
            <td><?php echo $conge->date_fin; ?></td>
            <td><?php echo $conge->mi_debut_journee; ?></td>
            <td><?php echo $conge->mi_fin_journee; ?></td>
            <td><?php echo $conge->nombre_jours; ?></td>
            <td><?php echo $conge->ferme; ?></td>
            <?php 
            if($profil === 'admin')
            {
            ?>
             <td>
                <a href="<?php echo $this->url(array('controller' => 'conge', 'action' => 'modifier', 'id' => $conge->id), 'default', true); ?>"><i  class="icon-pencil"></i></a>
             </td>
             <td>
                <i class="icon-remove" id="<?php echo $this->url(array('controller' => 'conge', 'action' => 'supprimer'), 'default', true); ?>"></i>
             </td>
             <?php  
            }
             ?>
        </tr>
        </tbody>
        <?php endforeach; ?>
    </table>
    <?php
    //nous affichons, à la suite du tableau (après la balise </table>), notre template qui permettra de gérer la pagination
    //la méthode pginationControl() prend, ici, 3 arguments:
    //  - l'instane paginator
    //  - le style de défilement
    //  - le template de pagination
    //echo$this->action('calendriermensuel','calendrier','application'); 
    echo $this->paginationControl($this->congeArray, 'Sliding', 'common/my_paginator_control.phtml');
	?>
</div>