
<?php //echo $this->action('calendriermensuel','calendrier','application'); ?>
	

	<div id ="bloc_choix_conge">
		<h4> <?php echo $this->escape($this->title); ?>  </h4>
				<div id="filtres_conge">
					<ol>
						</br>
						<li><strong>Nom Prenom</strong></li>
						</br>
						<li><strong>Date de debut</strong></li>
						</br>
						<li><strong>Debut Midi</strong></li>
						</br>
						<li><strong>Type De Conge</strong></li>
					</ol>			
				</div>
				<div id="filtres_conge2">
					<ol>
						</br>
						<li><strong>Date Fin</strong></li>
						</br>
						<li><strong>Fin Midi</strong></li>
						</br>
						<li><strong>Annee De Reference</strong></li>
						</br>
						<li><strong>Ferme</strong></li>
																									
					</ol>			
				</div>
	
	<?php echo $this->form; ?>	
	</div>


