<div>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Nom Prenom</th>
            <th>Type de conge</th>
            <th>Annee Reference</th>
            <th>Date Debut</th>
            <th>Date Fin</th>
            <th>Debut Journee</th>
            <th>Fin Journee</th>
            <th>Nombre Jours</th>
            <th>Ferme</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php

            //$this->usersArray est une variable qui peut être garnie par le controller
            //elle doit recevoir un tableau contenant des objets de type Default_Model_Users
            //le tableau est parcouru par foreach pour afficher les propiétés des objets contenus dans le tableau
            foreach ($this->congeArray as $conge) :
            $personne = new Default_Model_Personne();
			$result_set_personnes = $personne->find($conge->id_personne);
			$type = new Default_Model_TypeConge();
			$result_set_types = $type->find($conge->id_type_conge);
         
         ?>
        <tr>
            <td><?php echo $conge->id_personne; ?></td>
            <td><?php echo $result_set_personnes->getNom().'  '.$result_set_personnes->getPrenom(); ?></td>  
            <td><?php echo $result_set_types->getCode(); ?></td>
            <td><?php echo $conge->annee_reference; ?></td>
            <td><?php echo $conge->date_debut; ?></td>
            <td><?php echo $conge->date_fin; ?></td>
            <td><?php echo $conge->mi_debut_journee; ?></td>
            <td><?php echo $conge->mi_fin_journee; ?></td>
            <td><?php echo $conge->nombre_jours; ?></td>
            <td><?php echo $conge->ferme; ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'conge', 'action' => 'edit', 'id' => $conge->id), 'default', true); ?>">Edit</a>
            </td>
           <td>
                <a href="<?php echo $this->url(array('controller' => 'conge', 'action' => 'delete', 'id' => $conge->id), 'default', true); ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php
    //nous affichons, à la suite du tableau (après la balise </table>), notre template qui permettra de gérer la pagination
    //la méthode pginationControl() prend, ici, 3 arguments:
    //  - l'instane paginator
    //  - le style de défilement
    //  - le template de pagination
    echo$this->action('calendriermensuel','calendrier','application'); 
    echo $this->paginationControl($this->congeArray, 'Sliding', 'common/my_paginator_control.phtml');
	?>
</div>