<div >
 <div class = "Table_Afficher_Valider">  <!--  MTA / Mohamed khalil Takafi  -->
    <table border="1">
    
        <tr>
            
            <th>Nom Prenom</th>
            <th>date_debut</th>
            <th>date_fin</th>
            <th>nombre_jours</th>
            <th>etat</th>
            <th>Accepter</th>
            <th>Refuser</th>
            
        </tr>
        <?php
            //$this->usersArray est une variable qui peut être garnie par le controller
            //elle doit recevoir un tableau contenant des objets de type Default_Model_Proposition
            //le tableau est parcouru par foreach pour afficher les propiétés des objets contenus dans le tableau
            foreach ($this->propositionArray as $proposition) :
        	$personne = new Default_Model_Personne();
			$result_set_personnes = $personne->find($proposition->id_personne);
        ?>
        <tr>
        		
           
            <td><?php echo$result_set_personnes->getNom().'  '.$result_set_personnes->getPrenom(); ?></td>
            <td><?php echo $proposition->date_debut; ?></td>
            <td><?php echo $proposition->date_fin; ?></td>
            <td><?php echo $proposition->nombre_jours; ?></td>
            <td><?php echo $proposition->etat; ?></td>

             <td>
                <a href="<?php echo $this->url(array('controller' => 'proposition', 'action' => 'accepter', 'id' => $proposition->id,'solde'=>2), 'default', true); ?>">Accepter</a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'proposition', 'action' => 'refuser', 'id' => $proposition->id), 'default', true); ?>">Refuser</a>
            </td>

        </tr>
        <?php endforeach; ?>
       
    </table>

</div>
    </br>    <!--  MTA / Mohamed khalil Takafi  -->
    <?php
    //nous affichons, à la suite du tableau (après la balise </table>), notre template qui permettra de gérer la pagination
    //la méthode pginationControl() prend, ici, 3 arguments:
    //  - l'instane paginator
    //  - le style de défilement
    //  - le template de pagination
    echo $this->paginationControl($this->propositionArray, 'Sliding', 'common/my_paginator_control.phtml');
	?>
</div>