
<?php //echo $this->action('calendriermensuel','calendrier','application'); ?>
	
<div id="content">
	<div id ="bloc_choix_proposition">
		<h4> <?php echo $this->escape($this->title);?>  </h4>
				<div id="filtres_proposition">
					<ol>
						</br>
						<li><strong>Nom Prenom</strong></li>
						</br>
						<li><strong>Date de debut</strong></li>
						</br>
						<li><strong>Fin Midi</strong></li>
						</br>
						<li><strong>Date Fin</strong></li>
						</br>
						<li><strong>Debut Midi</strong></li>
					</ol>			
				</div>
              
	
	<?php 
	
	var_dump($this->var); 
	echo $this->form;
	       ?>	
	</div>


</div>